# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SpecpowerUI0_5.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1126, 704)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/test_96px_1154013_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(420, 10, 334, 25))
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(10, 360, 341, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(10, 230, 341, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.tW_SUT = QtWidgets.QTableWidget(Form)
        self.tW_SUT.setGeometry(QtCore.QRect(370, 260, 741, 441))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tW_SUT.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tW_SUT.setFont(font)
        self.tW_SUT.setFrameShape(QtWidgets.QFrame.Panel)
        self.tW_SUT.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tW_SUT.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tW_SUT.setAlternatingRowColors(False)
        self.tW_SUT.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tW_SUT.setObjectName("tW_SUT")
        self.tW_SUT.setColumnCount(9)
        self.tW_SUT.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_SUT.setItem(2, 0, item)
        self.tW_SUT.horizontalHeader().setDefaultSectionSize(150)
        self.tW_SUT.horizontalHeader().setStretchLastSection(True)
        self.tW_CCS = QtWidgets.QTableWidget(Form)
        self.tW_CCS.setGeometry(QtCore.QRect(370, 190, 741, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tW_CCS.setFont(font)
        self.tW_CCS.setAutoFillBackground(False)
        self.tW_CCS.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tW_CCS.setAlternatingRowColors(False)
        self.tW_CCS.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tW_CCS.setObjectName("tW_CCS")
        self.tW_CCS.setColumnCount(7)
        self.tW_CCS.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tW_CCS.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_CCS.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_CCS.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_CCS.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_CCS.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_CCS.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_CCS.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_CCS.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_CCS.setItem(0, 0, item)
        self.tW_CCS.horizontalHeader().setCascadingSectionResizes(False)
        self.tW_CCS.horizontalHeader().setDefaultSectionSize(150)
        self.tW_CCS.horizontalHeader().setSortIndicatorShown(False)
        self.tW_CCS.horizontalHeader().setStretchLastSection(True)
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(353, 50, 20, 651))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 341, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(78, 126, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.L_biosver = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.L_biosver.setFont(font)
        self.L_biosver.setObjectName("L_biosver")
        self.verticalLayout_5.addWidget(self.L_biosver)
        self.L_cpldver = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.L_cpldver.setFont(font)
        self.L_cpldver.setObjectName("L_cpldver")
        self.verticalLayout_5.addWidget(self.L_cpldver)
        self.L_bmcver = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.L_bmcver.setFont(font)
        self.L_bmcver.setObjectName("L_bmcver")
        self.verticalLayout_5.addWidget(self.L_bmcver)
        self.L_cputype = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.L_cputype.setFont(font)
        self.L_cputype.setObjectName("L_cputype")
        self.verticalLayout_5.addWidget(self.L_cputype)
        self.L_memtype = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.L_memtype.setFont(font)
        self.L_memtype.setObjectName("L_memtype")
        self.verticalLayout_5.addWidget(self.L_memtype)
        self.L_ssdtype = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.L_ssdtype.setFont(font)
        self.L_ssdtype.setObjectName("L_ssdtype")
        self.verticalLayout_5.addWidget(self.L_ssdtype)
        self.L_nvmetype = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.L_nvmetype.setFont(font)
        self.L_nvmetype.setObjectName("L_nvmetype")
        self.verticalLayout_5.addWidget(self.L_nvmetype)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 380, 341, 161))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.tB_testresult = QtWidgets.QTextBrowser(self.layoutWidget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.tB_testresult.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tB_testresult.setFont(font)
        self.tB_testresult.setObjectName("tB_testresult")
        self.verticalLayout_10.addWidget(self.tB_testresult)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar.setProperty("value", 10)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_10.addWidget(self.progressBar)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 550, 341, 151))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.tB_failinfo = QtWidgets.QTextBrowser(self.layoutWidget2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.tB_failinfo.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tB_failinfo.setFont(font)
        self.tB_failinfo.setObjectName("tB_failinfo")
        self.verticalLayout_11.addWidget(self.tB_failinfo)
        self.layoutWidget3 = QtWidgets.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(370, 160, 181, 25))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_22.addWidget(self.label_3)
        self.lcdN_testtime = QtWidgets.QLCDNumber(self.layoutWidget3)
        self.lcdN_testtime.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lcdN_testtime.setFont(font)
        self.lcdN_testtime.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdN_testtime.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdN_testtime.setDigitCount(8)
        self.lcdN_testtime.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdN_testtime.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdN_testtime.setProperty("value", 0.0)
        self.lcdN_testtime.setProperty("intValue", 0)
        self.lcdN_testtime.setObjectName("lcdN_testtime")
        self.horizontalLayout_22.addWidget(self.lcdN_testtime)
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(740, 50, 20, 111))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(880, 50, 20, 111))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pB_start = QtWidgets.QPushButton(Form)
        self.pB_start.setGeometry(QtCore.QRect(910, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pB_start.setFont(font)
        self.pB_start.setObjectName("pB_start")
        self.pB_exit = QtWidgets.QPushButton(Form)
        self.pB_exit.setGeometry(QtCore.QRect(1020, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pB_exit.setFont(font)
        self.pB_exit.setObjectName("pB_exit")
        self.pB_logupload = QtWidgets.QPushButton(Form)
        self.pB_logupload.setGeometry(QtCore.QRect(1020, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pB_logupload.setFont(font)
        self.pB_logupload.setObjectName("pB_logupload")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(630, 170, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.L_logPath = QtWidgets.QLabel(Form)
        self.L_logPath.setGeometry(QtCore.QRect(690, 170, 421, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.L_logPath.setFont(font)
        self.L_logPath.setObjectName("L_logPath")
        self.pB_1checkSUTconfig = QtWidgets.QPushButton(Form)
        self.pB_1checkSUTconfig.setGeometry(QtCore.QRect(760, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pB_1checkSUTconfig.setFont(font)
        self.pB_1checkSUTconfig.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pB_1checkSUTconfig.setAutoFillBackground(False)
        self.pB_1checkSUTconfig.setCheckable(False)
        self.pB_1checkSUTconfig.setObjectName("pB_1checkSUTconfig")
        self.pB_2ResetSUTostime = QtWidgets.QPushButton(Form)
        self.pB_2ResetSUTostime.setGeometry(QtCore.QRect(760, 130, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pB_2ResetSUTostime.setFont(font)
        self.pB_2ResetSUTostime.setObjectName("pB_2ResetSUTostime")
        self.layoutWidget4 = QtWidgets.QWidget(Form)
        self.layoutWidget4.setGeometry(QtCore.QRect(372, 52, 84, 72))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_67 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.verticalLayout.addWidget(self.label_67)
        self.rB_TT_sepc = QtWidgets.QRadioButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rB_TT_sepc.setFont(font)
        self.rB_TT_sepc.setObjectName("rB_TT_sepc")
        self.verticalLayout.addWidget(self.rB_TT_sepc)
        self.rB_TT_ptu = QtWidgets.QRadioButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rB_TT_ptu.setFont(font)
        self.rB_TT_ptu.setObjectName("rB_TT_ptu")
        self.verticalLayout.addWidget(self.rB_TT_ptu)
        self.layoutWidget5 = QtWidgets.QWidget(Form)
        self.layoutWidget5.setGeometry(QtCore.QRect(480, 52, 121, 99))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_66 = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.verticalLayout_2.addWidget(self.label_66)
        self.rB_TT_25c = QtWidgets.QRadioButton(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rB_TT_25c.setFont(font)
        self.rB_TT_25c.setObjectName("rB_TT_25c")
        self.verticalLayout_2.addWidget(self.rB_TT_25c)
        self.rB_TT_30c = QtWidgets.QRadioButton(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rB_TT_30c.setFont(font)
        self.rB_TT_30c.setObjectName("rB_TT_30c")
        self.verticalLayout_2.addWidget(self.rB_TT_30c)
        self.rB_TT_35c = QtWidgets.QRadioButton(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rB_TT_35c.setFont(font)
        self.rB_TT_35c.setObjectName("rB_TT_35c")
        self.verticalLayout_2.addWidget(self.rB_TT_35c)
        self.layoutWidget6 = QtWidgets.QWidget(Form)
        self.layoutWidget6.setGeometry(QtCore.QRect(620, 52, 116, 72))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_68 = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.verticalLayout_3.addWidget(self.label_68)
        self.rB_TM_highperf = QtWidgets.QRadioButton(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rB_TM_highperf.setFont(font)
        self.rB_TM_highperf.setObjectName("rB_TM_highperf")
        self.verticalLayout_3.addWidget(self.rB_TM_highperf)
        self.rB_TM_balance = QtWidgets.QRadioButton(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rB_TM_balance.setFont(font)
        self.rB_TM_balance.setObjectName("rB_TM_balance")
        self.verticalLayout_3.addWidget(self.rB_TM_balance)
        self.label_55 = QtWidgets.QLabel(Form)
        self.label_55.setGeometry(QtCore.QRect(10, 270, 93, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.label_53 = QtWidgets.QLabel(Form)
        self.label_53.setGeometry(QtCore.QRect(10, 340, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.layoutWidget7 = QtWidgets.QWidget(Form)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 240, 341, 22))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_3.addWidget(self.label_25)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.layoutWidget8 = QtWidgets.QWidget(Form)
        self.layoutWidget8.setGeometry(QtCore.QRect(110, 280, 98, 80))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.label_56 = QtWidgets.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_8.addWidget(self.label_56)
        self.label_57 = QtWidgets.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_8.addWidget(self.label_57)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_8.addWidget(self.label_15)
        self.layoutWidget9 = QtWidgets.QWidget(Form)
        self.layoutWidget9.setGeometry(QtCore.QRect(210, 280, 141, 81))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget9)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.L_cmip = QtWidgets.QLabel(self.layoutWidget9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.L_cmip.setFont(font)
        self.L_cmip.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.L_cmip.setWordWrap(True)
        self.L_cmip.setObjectName("L_cmip")
        self.verticalLayout_7.addWidget(self.L_cmip)
        self.L_cm_biosver = QtWidgets.QLabel(self.layoutWidget9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.L_cm_biosver.setFont(font)
        self.L_cm_biosver.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.L_cm_biosver.setObjectName("L_cm_biosver")
        self.verticalLayout_7.addWidget(self.L_cm_biosver)
        self.L_cm_psufw = QtWidgets.QLabel(self.layoutWidget9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.L_cm_psufw.setFont(font)
        self.L_cm_psufw.setObjectName("L_cm_psufw")
        self.verticalLayout_7.addWidget(self.L_cm_psufw)
        self.L_ccsip = QtWidgets.QLabel(self.layoutWidget9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.L_ccsip.setFont(font)
        self.L_ccsip.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.L_ccsip.setObjectName("L_ccsip")
        self.verticalLayout_7.addWidget(self.L_ccsip)
        self.pB_clear = QtWidgets.QPushButton(Form)
        self.pB_clear.setGeometry(QtCore.QRect(910, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pB_clear.setFont(font)
        self.pB_clear.setObjectName("pB_clear")
        self.pB_help = QtWidgets.QPushButton(Form)
        self.pB_help.setGeometry(QtCore.QRect(1020, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pB_help.setFont(font)
        self.pB_help.setObjectName("pB_help")
        self.pB_monitor = QtWidgets.QPushButton(Form)
        self.pB_monitor.setGeometry(QtCore.QRect(910, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pB_monitor.setFont(font)
        self.pB_monitor.setObjectName("pB_monitor")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(700, 20, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.pB_start.raise_()
        self.pB_exit.raise_()
        self.pB_logupload.raise_()
        self.label_2.raise_()
        self.L_logPath.raise_()
        self.pB_1checkSUTconfig.raise_()
        self.pB_2ResetSUTostime.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.label.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.tW_SUT.raise_()
        self.tW_CCS.raise_()
        self.line.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.label_55.raise_()
        self.label_53.raise_()
        self.pB_clear.raise_()
        self.pB_help.raise_()
        self.pB_monitor.raise_()
        self.label_16.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SpecPowerTool"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Lenovo Spec Power Test Tool</span></p></body></html>"))
        item = self.tW_SUT.horizontalHeaderItem(0)
        item.setText(_translate("Form", "IP Address"))
        item = self.tW_SUT.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Basic Config Check"))
        item = self.tW_SUT.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Call SSJ Script"))
        item = self.tW_SUT.horizontalHeaderItem(3)
        item.setText(_translate("Form", "FPGA Test"))
        item = self.tW_SUT.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Io Meter Test"))
        item = self.tW_SUT.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Call Pre-Del"))
        item = self.tW_SUT.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Call Basic Check Script"))
        item = self.tW_SUT.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Call Io Meter Script"))
        item = self.tW_SUT.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Call FPGA Script"))
        __sortingEnabled = self.tW_SUT.isSortingEnabled()
        self.tW_SUT.setSortingEnabled(False)
        self.tW_SUT.setSortingEnabled(__sortingEnabled)
        self.tW_CCS.setSortingEnabled(False)
        item = self.tW_CCS.verticalHeaderItem(0)
        item.setText(_translate("Form", "CCS   "))
        item = self.tW_CCS.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Call runccs.bat"))
        item = self.tW_CCS.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Call rundirector.bat"))
        item = self.tW_CCS.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Call runpower.bat"))
        item = self.tW_CCS.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Call runtemp.bat"))
        item = self.tW_CCS.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Call Wcs_get_fan.bat"))
        item = self.tW_CCS.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Call Wcs_get_temp.bat"))
        item = self.tW_CCS.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Call Wcs_get_psu.bat"))
        __sortingEnabled = self.tW_CCS.isSortingEnabled()
        self.tW_CCS.setSortingEnabled(False)
        self.tW_CCS.setSortingEnabled(__sortingEnabled)
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">SUT Stander Configuration：</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "BIOS Version:"))
        self.label_9.setText(_translate("Form", "CPLD Version:"))
        self.label_10.setText(_translate("Form", "BMC Version:"))
        self.label_11.setText(_translate("Form", "CPU:"))
        self.label_12.setText(_translate("Form", "Memory:"))
        self.label_14.setText(_translate("Form", "SSD:"))
        self.label_13.setText(_translate("Form", "Nvme:"))
        self.L_biosver.setText(_translate("Form", "From Config File"))
        self.L_cpldver.setText(_translate("Form", "TextLabel"))
        self.L_bmcver.setText(_translate("Form", "TextLabel"))
        self.L_cputype.setText(_translate("Form", "TextLabel"))
        self.L_memtype.setText(_translate("Form", "TextLabel"))
        self.L_ssdtype.setText(_translate("Form", "TextLabel"))
        self.L_nvmetype.setText(_translate("Form", "TextLabel"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Test Result Info：</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Test Fail Info：</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Test Time：</span></p></body></html>"))
        self.pB_start.setText(_translate("Form", "Start"))
        self.pB_exit.setText(_translate("Form", "Exit"))
        self.pB_logupload.setText(_translate("Form", "Log Upload"))
        self.label_2.setText(_translate("Form", "Log Path:"))
        self.L_logPath.setText(_translate("Form", "Default"))
        self.pB_1checkSUTconfig.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.pB_1checkSUTconfig.setText(_translate("Form", "1.Check SUT Config"))
        self.pB_2ResetSUTostime.setText(_translate("Form", "2.Reset SUT OS Time"))
        self.label_67.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Test Type:</span></p></body></html>"))
        self.rB_TT_sepc.setText(_translate("Form", "Specpower"))
        self.rB_TT_ptu.setText(_translate("Form", "PTU"))
        self.label_66.setText(_translate("Form", "<html><head/><body><p>Test Temperature :</p></body></html>"))
        self.rB_TT_25c.setText(_translate("Form", "25C"))
        self.rB_TT_30c.setText(_translate("Form", "30C"))
        self.rB_TT_35c.setText(_translate("Form", "35C"))
        self.label_68.setText(_translate("Form", "<html><head/><body><p>Test Mode:</p></body></html>"))
        self.rB_TM_highperf.setText(_translate("Form", "High Perfomance"))
        self.rB_TM_balance.setText(_translate("Form", "Balance"))
        self.label_55.setText(_translate("Form", "Chassis Manager"))
        self.label_53.setText(_translate("Form", "CCS"))
        self.label_25.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">CM &amp; CCS Stander Configuration:</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "IP:"))
        self.label_56.setText(_translate("Form", "BIOS Version："))
        self.label_57.setText(_translate("Form", "PSU FW Version："))
        self.label_15.setText(_translate("Form", "IP:"))
        self.L_cmip.setText(_translate("Form", "TextLabel"))
        self.L_cm_biosver.setText(_translate("Form", "TextLabel"))
        self.L_cm_psufw.setText(_translate("Form", "TextLabel"))
        self.L_ccsip.setText(_translate("Form", "TextLabel"))
        self.pB_clear.setText(_translate("Form", "Clear SUT"))
        self.pB_help.setText(_translate("Form", "Help"))
        self.pB_monitor.setText(_translate("Form", "Monitor"))
        self.label_16.setText(_translate("Form", "V1.0.0.0"))

